### ISSUE TITLE
Does not work with `serde_with`

### ISSUE THREAD

**Issue by laptou** [oscartbeaumont/specta#150]
When I try to use `#[derive(Type)]` and `#[serde_with::serde_as]` on the same structure, I get errors on every doc comment.

```rust
#[serde_as]
#[derive(Type)]
pub struct Example {
    /// this is a field
    field: usize,
}
```

This code gives an error on the doc comment:

> 
> ```
> error[E0659]: `doc` is ambiguous
>   --> core/src/sync/mod.rs:61:5
>    |
> 61 |     /// this is a field
>    |     ^^^^^^^^^^^^^^^^^^^ ambiguous name
>    |
>    = note: ambiguous because of a name conflict with a builtin attribute
>    = note: `doc` could refer to a built-in attribute
> note: `doc` could also refer to the derive helper attribute defined here
>   --> core/src/sync/mod.rs:59:10
>    |
> 59 | #[derive(Type)]
>    |          ^^^^
> 
> ```

**Comment by oscartbeaumont** [comment]
Which version of Specta are you using?

I assume this issue is the same as #97 which should be fixed on Specta's latest releases. I don't think `serde_as` is the problem here but feel free to prove me wrong.

Specta also does lack support for `serde_as` so this issue should stay open as a reminder of that. PR's are welcome or I will get to it when I have some free time!

**Comment by laptou** [comment]
I was using 1.0.5. Upgrading to 2.0.0-rc.3 fixed the issue. Thanks!

**Comment by laptou** [comment]
> Specta also does lack support for serde_as so this issue should stay open as a reminder of that.

I agree that `serde_as` isn't the issue here now that it's working, but I wasn't sure at first. I wanted to use `serde_as` to serialize big integers as strings - is there a recommended way to do it without `serde_as`?

**Comment by oscartbeaumont** [comment]
Related to #86
