### ISSUE TITLE
Add basic `bevy_ecs` Type support

### ISSUE THREAD

**Issue by bennoinbeta** [oscartbeaumont/specta#161]
https://docs.rs/bevy_ecs/latest/bevy_ecs/

**Comment by bennoinbeta** [comment]
And what where the reasons/thoughts behind renaming `Entity` to `EntityDef` (just curious) :)

**Comment by oscartbeaumont** [comment]
Whoops.

I have extended the unit tests so they would catch this sorta thing.

My goal with this rename was to make the bigint error message nicer but I have instead refactored how that system works in #180 to achieve the same result without requiring the invalid rename.

Should all be fixed in https://github.com/oscartbeaumont/specta/commit/72c8ee7287652eb42acb8698fa14364fcc1ec786

For renaming `Entity` to `EntityDef` I have been doing it out of habit because for most crates the types end up referring to each other so it's easier to just `use {crate}::{types}` at the top so I don't need to qualify them on each line.

Sorry about messing it up and thanks for reporting these issues!
