### ISSUE TITLE
Integration with wasm-bindgen

### ISSUE THREAD

**Issue by indietyp** [oscartbeaumont/specta#196]
Utilizing "typescript_custom_section" (https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/typescript_custom_section.html) we could emit type bindings directly.

This seems to be non-trivial though, as it requires a const string.

(btw sorry for all these issues, I am just very excited about this amazing project and its potential)

**Comment by oscartbeaumont** [comment]
This would be cool but I think it is way more difficult than you would expect.

Specta works fully at runtime making use of Rust's trait system to resolve types while Tauri bindgen works fully through static analysis which is just looking at the file content.

As a workaround, you could technically generate a `types.rs` file with the bindgen typescript section when your application starts up or in a unit test but you would then have to call the bindgen CLI again. I am assuming the bindgen CLI doesn't check if the file was actually imported (like `mod types;`) so you could probs still start your app to generate the file.

If Specta ever had a CLI we could definitely support this but I really don't think that will happen. Resolving types using static analysis would be both significantly less reliable and require us to maintain a completely different implementation.

For future me:
 - A Specta is hard because we can't rely on traits to resolve types like we can with the macros.
 - What if `impl uuid::Uuid for Type` (in an external crate) how can the CLI know we have an implementation for it?
 - A macro could shield the type (Eg. `a: some_type!()`) or a `pub struct String();` (replacing a std type in the same file), or declare types we can't see.
 - We could generate Rust code to resolve the types but it will be slow and at that point why wouldn't you just run your whole program or break the types out into another crate. I did a prototype of this on #200

**Comment by indietyp** [comment]
Yes, right now I don't think it is possible, the only real way I see this working would be with support in `wasm-pack` or `wasm-bindgen` for a post-processing step that then invokes a binary or function of some sort (or a specta CLI as mentioned). I don't see native support happening tho.

Right now, what I think the best way is (although a bit yank) is to have an example like `collect_types.rs`, which then prints the generated `.d.ts` and replace that one with the one that was generated by `wasm-bindgen`.

Another thing to mention is that the current `specta` proc-macro clashes with the `wasm_bindgen` macro (switching them just moved the problem elsewhere), but I don't see a way around that, as both change the generated output quite a bit.

**Comment by oscartbeaumont** [comment]
> current specta proc-macro clashes with the wasm_bindgen macro

Can you share the error, that is definitely something I can look into fixing.

**Comment by indietyp** [comment]
```rust
#[wasm_bindgen::prelude::wasm_bindgen]
#[specta::specta]
pub async fn create_account(
    client: &__wasm::AccountServiceClient,
    args: wasm_bindgen::JsValue,
) -> Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue> {
    let args: CheckAccountGroupPermission = serde_wasm_bindgen::from_value(args)?;

    let value =
        client.client.call(args).await.map_err(|error| {
            match serde_wasm_bindgen::to_value(&error) {
                Ok(value) => value,
                Err(error) => error.into(),
            }
        })?;

    serde_wasm_bindgen::to_value(&value).map_err(Into::into)
}

```

error:

```
error: specta: expected string literal. Eg. `"somestring"`
  --> libs/@local/hash-graph-rpc/src/specification/account.rs:29:1
   |
29 | #[wasm_bindgen::prelude::wasm_bindgen]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `wasm_bindgen::prelude::wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
```


and if we switch 'em:

```
#[specta::specta]
#[wasm_bindgen::prelude::wasm_bindgen]
pub async fn create_account(
    client: &__wasm::AccountServiceClient,
    args: wasm_bindgen::JsValue,
) -> Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue> {
    let args: CheckAccountGroupPermission = serde_wasm_bindgen::from_value(args)?;

    let value =
        client.client.call(args).await.map_err(|error| {
            match serde_wasm_bindgen::to_value(&error) {
                Ok(value) => value,
                Err(error) => error.into(),
            }
        })?;

    serde_wasm_bindgen::to_value(&value).map_err(Into::into)
}
```

error:

```
error: custom attribute panicked
  --> libs/@local/hash-graph-rpc/src/specification/account.rs:29:1
   |
29 | #[specta::specta]
   | ^^^^^^^^^^^^^^^^^
   |
   = help: message: Attribute path must be an ident
```

**Comment by oscartbeaumont** [comment]
Okay so found and fixed a couple of things.

Using `pub fn`'s with `specta::specta` was flat out broken - #205

and then given the input:
```rust
#[wasm_bindgen::prelude::wasm_bindgen]
#[specta]
pub fn testing() {}
```
Rust gives Specta the tokens:
```
"#[allow(dead_code)] pub fn testing() {}"
"pub unsafe extern \"C\" fn __wasm_bindgen_generated_testing() -> wasm_bindgen ::\nconvert :: WasmRet < < () as wasm_bindgen :: convert :: ReturnWasmAbi > :: Abi\n>\n{\n    let _ret = { let _ret = testing() ; _ret } ; < () as wasm_bindgen ::\n    convert :: ReturnWasmAbi > :: return_abi(_ret).into()\n}"
```

For this case, we can't really work out the types without reimplementing a bunch of the `wasm_bindgen` logic which I would rather not so I have put an error to make the DX a bit nicer.

<img width="1348" alt="Screenshot 2023-12-24 at 8 15 32 pm" src="https://github.com/oscartbeaumont/specta/assets/21004798/b4a8e72c-5711-4fba-b1cb-2b53e9071063">


While if you switch around the macros:
```rust
#[specta]
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn testing() {}
```
gives Specta the tokens:
```
#[wasm_bindgen :: prelude :: wasm_bindgen] pub fn testing() {}
```
and this was just broken due to a bug in Specta's macros parsing of paths (it tried to cast it to an ident). You could transform your code to the following and it should start working. I have fixed this on `main`.
```rust
#[specta]
#[wasm_bindgen]
pub fn demo() {}
```

Hopefully that helps!
