### ISSUE TITLE
Add an attribute for renaming structs

### ISSUE THREAD

**Issue by campbellcole** [oscartbeaumont/specta#53]
I am trying to use this crate along with the `tauri-specta` crate to build an app that is attached to an SQLite database. I am using `sea_orm` as my ORM and it has an interesting quirk where every model struct must be named `Model`. For example:
```rs
#[derive(Debug, Clone, PartialEq, DeriveEntityModel, Serialize, Deserialize, Type)]
#[sea_orm(table_name = "tests")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    pub description: String,
}
```

This is resulting in type declarations that contain errors because the exported types have the same name. I am using this crate to replace a needlessly complicated type generation system using `schemars::JsonSchema` which allows me to use the attribute: `#[schemars(title = "Test")]` and the type declaration will have that name. It would make sense to add an attribute within this crate instead of going the route of parsing yet another crates macro attributes, especially if this would be the only attribute you'd borrow from schemars. I will see about implementing this myself and submitting a pull request, and I will update here if I feel it is beyond my capabilities to do so. Thank you :)

**Comment by campbellcole** [comment]
My goodness. Been using Rust + serde for years and only just realized I can rename an entire struct using serde. I apologize for my ignorance. The `#[serde(rename = "Test")]` attribute solved my problem.

**Comment by oscartbeaumont** [comment]
Easily mistake to make! I need to make a one-stop location in the documentation for all supported attributes and their behaviors so they are easier to find.

Specta has done its best to copy serde's conventions because having compatibility is very nice for most usecases. You could have also done `#[specta(rename = "Test")]` in that case if you didn't want it to effect serde but I don't think that matters for SeaORM so either is fine.
