### ISSUE TITLE
Incorrect type definitions for `std::time::{SystemTime, Instant, Duration}`

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [oscartbeaumont/specta#77]
`SystemTime` and `Duration` are serialized as two-field objects, not strings. `Instant` doesn't support serialization at all, see https://github.com/serde-rs/serde/issues/1375.

```
[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
specta = "1.0.4"
```
```rust
#[derive(serde::Serialize)]
#[derive(specta::Type)]
struct MyStruct {
    st: std::time::SystemTime,
    // i: std::time::Instant,
    d: std::time::Duration,
}

fn main() {
    println!("{}", specta::ts::export::<MyStruct>(&Default::default()).unwrap());
    println!();
    let s = MyStruct {
        st: std::time::SystemTime::now(),
        d: std::time::Duration::from_secs(1),
    };
    println!("{}", serde_json::to_string_pretty(&s).unwrap());
}
```
```
export type MyStruct = { st: string; d: string }

{
  "st": {
    "secs_since_epoch": 1684393811,
    "nanos_since_epoch": 203204000
  },
  "d": {
    "secs": 1,
    "nanos": 0
  }
}
```

**Comment by oscartbeaumont** [comment]
Great spot will get these fixed and do a release!

Fixing this does raise an interesting question. From looking into Serde's codebase both `SystemTime` and `Duration` output  basically `{ field1: u64, field2: u32 }`. Now `u64` is a "bigint" type which Specta's Typescript exporter doesn't support by default to prevent people from shooting themselves in the foot as `JSON.parse`ing a bigint type *can* cause truncation.

By adding a "bigint" type to a default impl it would make the `export` feature of Specta useless unless you have bigint support enabled which is definitely not something I would want to do.

We could come up with a system so we can add this as an exception to the rule but that is also not really a prefect solution, alternatively we could require a feature to enable these impls but that also isn't perfect because you would kinda of expect all standard types to *just work* out of the box.

**Comment by oscartbeaumont** [comment]
After chatting with @Brendonovich he pointed out that the export system should lazily include standard library types which in hindsight is probably a bug. I have just fixed that. I have also decided that  `SystemTime` and `Duration` are to be treated as "bigint" types given Specta's general focus on correctness.

If you include a `SystemTime` or `Duration` in your schema you will be required to specify how you want to handle them through [BigIntExportBehavior](https://docs.rs/specta/latest/specta/ts/enum.BigIntExportBehavior.html). Will try and do a release this afternoon with these changes.

**Comment by avsaase** [comment]
What is the current state of this? I'm generating Typescript types for a rust struct that has a `Duration` field and on the TS side I'm just getting an `Object` type.

**Comment by oscartbeaumont** [comment]
Should be supported in [1.0.5](https://github.com/oscartbeaumont/specta/releases/tag/v1.0.5) so update your project.

@avsaase What do you mean by `[object Object]` because I don't think that is something Specta is capable of outputting?
