### ISSUE TITLE
Question: exporting a type from an instance of some data?

### ISSUE THREAD

**Issue by rvcas** [oscartbeaumont/specta#89]
In my case, I have some types for constructing a kind of json schema. So the annotations aren't exactly what I would use because the structs and enums aren't what needs to be exported, instead I would like to be able to export using the data that is contained in these types once instantiated. Is this something that's possible?

**Comment by oscartbeaumont** [comment]
You can for sure but be aware that any _major_ version change to Specta will likely require changes to your exporter although this shouldn't be often. We have started work on Specta v2 but it's probs gonna be a while before it's stabilisation and if your code is open source I can lend a hand upgrading.

You'll want to start with the [`Type`](https://docs.rs/specta/latest/specta/type/trait.Type.html) trait and it's the entrypoint to the system. Specta has many type exporters so I would give [them](https://github.com/oscartbeaumont/specta/blob/main/src/lang/ts/mod.rs) a look to see what you would need to do. The Typescript exporter is the only stable exporter but the other languages may make it a bit clearer what's going on because they are incomplete.

I would be curious how Specta's data model goes with expressing the format you are exporting as. We have a very TS-centric AST and I would personally like to make it more Rust-centric in the future.

**Comment by rvcas** [comment]
Hey @oscartbeaumont thanks for the reply. This is most certainly open source https://github.com/aiken-lang/aiken. The way this works is that this language compiles to a super super niche VM and other languages need to invoke it. The types of the arguments to your external facing functions (called validators) are lost during compilation and so we produce something called a blueprint which is much like an openapi for your "validator". We want to take things a step further and produce types for these validator arguments in arbitrary languages. Thanks for the reply. I'll check out what you've linked to and see what I can do. Much appreciated. I can close this issue if you'd like it to not clutter things.

**Comment by rvcas** [comment]
I checked out `Type` and that doesn't seem to take `self` which I think I would need to then manually construct things based on the runtime data we load from a blueprint file. Perhaps I can just build an `ExportConfiguration` manually? Essentially there's nothing for us to annotate, if we annotated the blueprint type that wouldn't produce that correct interface for the Aiken developer's "validator".

**Comment by oscartbeaumont** [comment]
Type exporting doesn't need to take `self` as it is designed so that you can export the types prior to constructing the runtime value of the type. Technically [`DataTypeFrom`](https://docs.rs/specta/latest/specta/derive.DataTypeFrom.html) kinda does exporting with `self` but this works very differently from `Type`, and is designed to let you construct an arbitrary Specta Type at runtime and as opposed to exporting a type constructed by the `specta::Type` macro.

You can also infer the type from a value like this:
```rs
fn export<T: Type>(t: T) {
   // Use the `T::inline` or `T::definition`.
}
```

**Comment by rvcas** [comment]
@oscartbeaumont oh perfect that's EXACTLY what I would need. Thank you so much for the replies.
